NumPy array is a central data structure of the numpy library (“Numeric Python”)
It is a high-performance multidimensional array object that is a powerful data structure for efficient computation of arrays and matrices.

In [28]:
import numpy as np

In [31]:
# an array contains information about the raw data, how to locate an element and how to interpret an element.
intArray = np.array([1,2,3,4,5])
print ( "First data pointer",intArray.data, "Type of elements",intArray.dtype, "Rows and Column Tuple" ,intArray.shape , 
        "Number of bytes per element",intArray.strides, "Dimension", intArray.ndim , "Size each element (bytes)" , intArray.itemsize)
intArray = np.array([[1,2,3],[4,5,6],[7,8,9]])
print ( "First data pointer",intArray.data, "Type of elements",intArray.dtype, "Rows and Column Tuple" ,intArray.shape , 
        "Number of bytes per element",intArray.strides, "Dimension", intArray.ndim , "Size each element (bytes)" , intArray.itemsize)

First data pointer <memory at 0x000000000776C708> Type of elements int32 Rows and Column Tuple (5,) Number of bytes per element (4,) Dimension 1 Size each element (bytes) 4
First data pointer <memory at 0x00000000077E1480> Type of elements int32 Rows and Column Tuple (3, 3) Number of bytes per element (12, 4) Dimension 2 Size each element (bytes) 4


In [4]:
### Creating arrays by inbuilt funtions
print( "Zero Matrix \n" , np.zeros((2,2)) ,"\n Ones Matrix \n", np.ones((2,2)) , "\n Full Matrix \n",np.full((2,2) , 0.35))

Zero Matrix 
 [[0. 0.]
 [0. 0.]] 
 Ones Matrix 
 [[1. 1.]
 [1. 1.]] 
 Full Matrix 
 [[0.35 0.35]
 [0.35 0.35]]


In [5]:
randomNumbers = np.random.random((4,4))
print (randomNumbers) ## A Randomly Created Numpy Array

[[0.38875181 0.17695549 0.13910923 0.34142063]
 [0.50311819 0.44630408 0.81787897 0.89992629]
 [0.62419932 0.94319615 0.93011053 0.84811184]
 [0.27039588 0.34289579 0.45854482 0.42147275]]


In [6]:
## Slicing and Dicing arrays
print ("\n Suset \n",randomNumbers[:2,1:3] , "\n Last  column \n " , randomNumbers[:,3] , "\n Second Row \n" , randomNumbers[1,:])


 Suset 
 [[0.17695549 0.13910923]
 [0.44630408 0.81787897]] 
 Last  column 
  [0.34142063 0.89992629 0.84811184 0.42147275] 
 Second Row 
 [0.50311819 0.44630408 0.81787897 0.89992629]


In [7]:
## Converting randomNumbers to float data type
print(randomNumbers.astype(int) + 10)


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [35]:
print(1 - randomNumbers)


[[0.61124819 0.82304451 0.86089077 0.65857937]
 [0.49688181 0.55369592 0.18212103 0.10007371]
 [0.37580068 0.05680385 0.06988947 0.15188816]
 [0.72960412 0.65710421 0.54145518 0.57852725]]
8.552391765116024
[1.78646519 1.90935151 2.34564355 2.51093151]
[1.04623716 2.66722753 3.34561783 1.49330924]


In [11]:
import sys
np500 = np.arange(500)
print("Space Occupied By Lists :", sys.getsizeof(1)* len(range(500)) ,"\nSpace Occupied by similar numpy array :" , np500.size * np500.itemsize)

Space Occupied By Lists : 14000 
Space Occupied by similar numpy array : 2000


In [27]:
import time;
SIZE = 10000000
list1 = range(SIZE)
list2 = range(SIZE)

stime = time.time()
#from itertools import chain
#result = chain(list1,list2)
result = [(x,y) for x,y in zip(list1,list2)]
print((time.time()-stime)* 1000)

npArray1 = np.arange(SIZE)
npArray2 = np.arange(SIZE)

stime = time.time()
result = npArray1 + npArray2
print((time.time()-stime)* 1000)

8416.481494903564
1570.0898170471191


In [40]:
numbers = np.array([(1,2,3),(4,5,6)])
print(numbers.sum())
print(numbers.sum(axis=0))
print(numbers.sum(axis=1))
print(np.sqrt(numbers))

21
[5 7 9]
[ 6 15]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
