NumPy array is a central data structure of the numpy library (“Numeric Python”)
It is a high-performance multidimensional array object that is a powerful data structure for efficient computation of arrays and matrices.

In [1]:
import numpy as np

In [7]:
# an array contains information about the raw data, how to locate an element and how to interpret an element.
intArray = np.array([1,2,3,4,5])
print ( "First data pointer",intArray.data, "Type of elements",intArray.dtype, "Rows and Column Tuple" ,intArray.shape , 
        "Number of bytes per element",intArray.strides)
intArray = np.array([[1,2,3],[4,5,6],[7,8,9]])
print ( "First data pointer",intArray.data, "Type of elements",intArray.dtype, "Rows and Column Tuple" ,intArray.shape , 
        "Number of bytes per element",intArray.strides)

First data pointer <memory at 0x000000000780CA08> Type of elements int32 Rows and Column Tuple (5,) Number of bytes per element (4,)
First data pointer <memory at 0x000000000777C1F8> Type of elements int32 Rows and Column Tuple (3, 3) Number of bytes per element (12, 4)


In [12]:
### Creating arrays by inbuilt funtions
print( "Zero Matrix \n" , np.zeros((2,2)) ,"\n Ones Matrix \n", np.ones((2,2)) , "\n Full Matrix \n",np.full((2,2) , 0.35))

Zero Matrix 
 [[0. 0.]
 [0. 0.]] 
 Ones Matrix 
 [[1. 1.]
 [1. 1.]] 
 Full Matrix 
 [[0.35 0.35]
 [0.35 0.35]]


In [19]:
randomNumbers = np.random.random((4,4))
print (randomNumbers) ## A Randomly Created Numpy Array

[[0.14259711 0.95960792 0.94830958 0.45590066]
 [0.05165813 0.30619392 0.12064982 0.47004061]
 [0.05051426 0.63964934 0.3135699  0.30954122]
 [0.24110701 0.7397199  0.90502701 0.44176673]]


In [27]:
## Slicing and Dicing arrays
print ("\n Suset \n",randomNumbers[:2,1:3] , "\n Last  column \n " , randomNumbers[:,3] , "\n Second Row \n" , randomNumbers[1,:])


 Suset 
 [[0.95960792 0.94830958]
 [0.30619392 0.12064982]] 
 Last  column 
  [0.45590066 0.47004061 0.30954122 0.44176673] 
 Second Row 
 [0.05165813 0.30619392 0.12064982 0.47004061]


In [32]:
## Converting randomNumbers to float data type
print(randomNumbers.astype(int) + 10)


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [33]:
print(1 - randomNumbers)

[[0.85740289 0.04039208 0.05169042 0.54409934]
 [0.94834187 0.69380608 0.87935018 0.52995939]
 [0.94948574 0.36035066 0.6864301  0.69045878]
 [0.75889299 0.2602801  0.09497299 0.55823327]]
